# project_id        = "dtonic-demo-k8s"
# region            = "europe-north1"
# db_instance_name  = "datatonic-db"
# db_user           = "admin"
# db_password       = "admin"
# db_version        = "MYSQL_8_0"